### ISSUE TITLE
Discussion of testtypes

### ISSUE THREAD

**Issue by vsoch** [HPC-buildtest/schemas#4]
I'm thinking through the test types, and I want to discuss the ones that currently exist (and what the names mean?) For example, `singlesource` implies that there could be a build with more than one source `multisource`? I would propose that we start with something like:

 - singlesource: refers to a single binary / executable to be run / tested (doesn't require a compiler, etc., and even could reference a container binary)
 - singlecompile: refers to a single script to be compiled first (requires compiler, etc.)

But if we are modeling different ways to compile things, instead of overloading that into a single class, why not have an explicit specification of the different kinds?

 - `compilerGnu`
 - `compilerIntel`
 - `compilerClang`
 - `compilerCuda`

Or something along those lines. Also, what would distinguish single from multi (or something else)? I'd like to discuss these details so we can create a namespace of testing schemas for different recipes. For example, if we want to make something really easy for a user to run a singularity test against a container, they would maybe do something like:

```bash
test_container:
  type: singularity
  description: "test running Singularity container"
  image: "docker://busybox"
  binds:
     - input:/one
     - output:/one
  post_build:
      # do something to assert that output was generated
```
This is starting to look a lot like some of the configs you'd see in travis or Circle, no? I'm even wondering (now that I see your pre_ ad post_ sections) if there is a way we can write the structure so some of it could be plugged in to a CI service. I suppose given that the above works, the user could run it on the CI:

```bash
buildtest build -c containers/singularity.yml
```
I can understand now why you were interested in having module control, because you'd want to load dependencies. I agree with your decision to refactor it out - I actually (after looking closely here) don't think that it belongs here. I could very easily use buildtest in ways that don't require modules at all (the container example above). So I think our list of TODOS:

 1. choose a yaml validator that we like
 2. Discuss the names / types here
 3. After 1 and 2 I'll write some draft proposals to discuss
 4. The schemas are integrated into buildtest
 5. Lmod should not be a requirement (e.g., I should be able to run / use buildtest on my local machine without it exiting as it currently does).

@shahzebsiddiqui

**Comment by shahzebsiddiqui** [comment]
@vsoch 

I like the use of `type` instead of `testtype` to select different schema to validate the subtest. I refer to subtest as `test_container` in the YAML file which is the top level key that you shared above.

Before we dive into a `type: singularity` i was thinking first to have a simple schema where user can write a shell script using YAML. This targets SysAdmin and end user who want to use buildtest to write scripts in YAML which can be used be shared but most likely would be site specific. I see this could be useful for acceptance testing. 

For example we have a simple YAML file that a site can use do write several checks

```
login_node_check:
  type: script
  script: 
    - "ping login1"
    - "ping login2"
    - "ping login3"

slurm_check:
  type: script
  script:
   - "systemctl is-active slurmd"
   - "systemctl is-enabled slurmd | grep enabled"
```

By far this is very simple schema for schema `type: script` but certainly we can add extra keys to instruct lets say the following:

- Which host to run script (defaults to localhost)
- Should test run against a batch scheduler, if so one or more partitions? 
- Specify if a test should have a dependency. For instance if `slurm_check` passes then you can run other sub-test that  depend on `slurm_check` to pass that are slurm specific test.

I think we should first develop this schema that i mentioned above `type: script` and then go for more elaborate schema types. 

I can see some benefit of having some schema types like for `container: singularity` but i dont know how user can do something elaborate such as running arbitrary command before and after. We can discuss that at later point.

**Comment by vsoch** [comment]
> Before we dive into a type: singularity i was thinking first to have a simple schema where user can write a shell script using YAML. 

Totally agree! That was a random example - I think if someone really wanted to implement a custom type like that, they should be able to.

When you say:

>     Specify if a test should have a dependency. For instance if slurm_check passes then you can run other sub-test that depend on slurm_check to pass that are slurm specific test.

It sounds like you are re-implementing snakemake, which represents a proper DAG and then runs a workflow (taking account for dependencies). Is that what you want to do? It sounds a lot like it's (really) a workflow manager, but instead of managing inputs and outputs, we are moving forward just based on a return codes. But then what happens if there are inputs/outputs from the tests? Is this any different than a workflow manager for HPC (which arguably, there are already many that exist?)

**Comment by vsoch** [comment]
Let's start with script for now, and we'll add test config types as they are needed.
